// Generate src/api/schema.d.ts from ../schemas/openapi.json with openapi-typescript.
//
// The output starts with a header naming the SHA-256 of the OpenAPI file it was built
// from; `tests/test_phase8.py` on the Python side and `npm run check:api` here both fail
// when that hash no longer matches, so a stale client cannot slip through CI.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const specPath = fileURLToPath(new URL("../../schemas/openapi.json", import.meta.url));
const outPath = fileURLToPath(new URL("../src/api/schema.d.ts", import.meta.url));
const check = process.argv.includes("--check");

const spec = readFileSync(specPath, "utf8");
const hash = createHash("sha256").update(spec).digest("hex");
const header = `// Generated by web/scripts/gen-api.mjs from schemas/openapi.json — do not edit.\n// openapi-sha256: ${hash}\n`;

if (check) {
  if (!existsSync(outPath)) {
    console.error("src/api/schema.d.ts is missing; run `npm run gen:api`");
    process.exit(1);
  }
  const current = readFileSync(outPath, "utf8");
  if (!current.includes(`openapi-sha256: ${hash}`)) {
    console.error("src/api/schema.d.ts is stale; run `npm run gen:api`");
    process.exit(1);
  }
  console.log("api client is current");
  process.exit(0);
}

const ast = await openapiTS(JSON.parse(spec), { alphabetize: true, defaultNonNullable: false });
writeFileSync(outPath, header + astToString(ast));
console.log(`wrote ${outPath}`);
